name: freemium_novels_app
description: A Flutter app for reading freemium novels.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.2
  twitter_login: ^4.4.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  shared_preferences: ^2.2.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
